name: Run_Tests

on: 
  push:
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }} 
    strategy:
      fail-fast: false
      matrix:
        config:          
          - { os: windows-latest, name: Windows cl Debug,                 cc: cl,       cxx: cl,                                                       build_type: Debug,     sudo: } 
          - { os: windows-latest, name: Windows cl Release,               cc: cl,       cxx: cl,                                                       build_type: Release,   sudo: }
          - { os: windows-latest, name: Windows clang Debug,              cc: clang-cl, cxx: clang-cl,                                                 build_type: Debug,     sudo: }
          - { os: windows-latest, name: Windows clang Release,            cc: clang-cl, cxx: clang-cl,                                                 build_type: Release,   sudo: }   
          

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout Catch
      uses: actions/checkout@v2
      with:
        repository: 'catchorg/Catch2'
        ref: 'v2.x'
        path: Catch2

    - name: Install Catch
      run: |
        cd Catch2
        cmake -Bbuild -S. -DBUILD_TESTING=OFF
        ${{ matrix.config.sudo }} cmake --build build/ --target install
      

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake ${{runner.workspace}}/Units/main/tests -DCMAKE_BUILD_TYPE="${{ matrix.config.build-type }}" -DCMAKE_CXX_COMPILER="${{ matrix.config.cxx }}"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config "${{ matrix.config.build-type }}"

    - name: Test (*nix)
      working-directory: ${{runner.workspace}}/build
      if: matrix.config.os != 'windows-latest'
      # Execute tests defined by the CMake configuration. 
      run: cmake --build . --config "${{ matrix.config.build-type }}" --target test

    - name: Test (Windows)
      working-directory: ${{runner.workspace}}/build
      if: matrix.config.os == 'windows-latest'
      # Execute tests defined by the CMake configuration. 
      run: cmake --build . --config "${{ matrix.config.build-type }}" --target RUN_TESTS