name: Run_Tests

on: 
  push:
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, windows-latest, macos-10.15, macos-11.0]        
        build-type: [Debug, Release]
        include:
        - os: ubuntu-20.04
          cxx: [g++ 7.5, g++ 8.4, g++ 9.3, g++ 10.2, clang++ 8.0.1, clang++ 9.0, clang++ 10.0.1]
        - os: ubuntu-18.04
          cxx: [g++ 7.5, g++ 8.4, g++ 9.3, g++ 10.1, clang++ 6.0, clang++ 8.0, clang++ 9.0]
        - os: ubuntu-16.04
          cxx: [g++ 7.5, g++ 8.4, g++ 9.3, clang++ 6.0, clang++ 8.0, clang++ 9.0]
        - os: macos-10.15
          cxx: [g++ 7.5, g++ 8.4, g++ 9.3, g++ 10.1, clang++ 6.0, clang++ 8.0, clang++ 9.0]
        - os: macos-11.0
          cxx: [cxx, gcc-8, gcc-9, clang++]
          

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout Catch
      uses: actions/checkout@v2
      with:
        repository: 'catchorg/Catch2'
        ref: 'v2.x'
        path: Catch2

    - name: Install Catch (*nix)
      if: matrix.os != 'windows-latest'
      run: |
        cd Catch2
        cmake -Bbuild -S. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install

    - name: Install Catch (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd Catch2
        cmake -Bbuild -S. -DBUILD_TESTING=OFF
        cmake --build build/ --target install
      

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake (Windows)
      working-directory: ${{runner.workspace}}/build
      if: matrix.os == 'windows-latest'
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake ${{runner.workspace}}/Units/main/tests -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: Configure CMake (*nix)
      working-directory: ${{runner.workspace}}/build
      if: matrix.os != 'windows-latest'
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake ${{runner.workspace}}/Units/main/tests -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} 

    - name: Build
      working-directory: ${{runner.workspace}}/build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE


    - name: Test (*nix)
      working-directory: ${{runner.workspace}}/build
      if: matrix.os != 'windows-latest'
      # Execute tests defined by the CMake configuration. 
      run: cmake --build . --config $BUILD_TYPE --target test

    - name: Test (Windows)
      working-directory: ${{runner.workspace}}/build
      if: matrix.os == 'windows-latest'
      # Execute tests defined by the CMake configuration. 
      run: cmake --build . --config $BUILD_TYPE --target RUN_TESTS